### ISSUE TITLE
findSedra should work better

### ISSUE THREAD

**Issue by Scimonster** [hebcal/hebcal-js#17]
```
var year = new Hebcal(5775); // define the year

year.findSedra('Miketz') // good
year.findSedra('miketz') // not found
year.findSedra('מקץ') // not found
year.findSedra('מקצ','h') // not found
year.findParsha('Shemos','a') // good
year.findParsha('Shemos') // nope
```

Expected behavior: Find the parsha regardless of spelling.

**Comment by MosheBerman** [comment]
Can you please detail the fixes, since your commit says "partially fixes?"

**Comment by Scimonster** [comment]
@MosheBerman Now it searches all spellings, but is still case sensitive.

```js
year.findSedra('Miketz') // good
year.findSedra('miketz') // not found
year.findSedra('מקץ') // found -- new!
year.findSedra('מקצ','h') // not found
year.findParsha('Shemos','a') // good
year.findParsha('Shemos') // found -- new!
```

**Comment by MosheBerman** [comment]
What do the 'h', and 'a' arguments do?

**Comment by MosheBerman** [comment]
Ah, cool! What do the 'h', and 'a' arguments do?

**Comment by MosheBerman** [comment]
I'm thinking that you can do some basic operations to solve this. For the english strings, storing them as all lowercase, then lowercasing any english search string would solve the problem. And replacing the 5 end characters for your מקץ/מקצ case should also be fairly simple. The principle is the same:

Pick a canonical storage format and convert any incoming queries to that format.

I'm not sure if I'm going to break things by changing your arrays. Does anything else depend on that code being uppercase or spelled a specific way?
