### ISSUE TITLE
TypeError: invalid pid after each hebcaljs command

### ISSUE THREAD

**Issue by ashersz** [hebcal/hebcal-js#27]
Hi,
I just installed hebcal thru npm global on a mac and I always get the following error after the hebcaljs command e.g.
$  hebcaljs -T
9 Iyyar 5776

Times:
  Chatzot            Mon May 16 2016 14:57:46 GMT+0300 (IDT) 
  Chatzot Night      Mon May 16 2016 02:57:45 GMT+0300 (IDT) 
  Alot Hashachar     Mon May 16 2016 07:49:28 GMT+0300 (IDT) 
  Misheyakir         Mon May 16 2016 08:09:01 GMT+0300 (IDT) 
  Misheyakir Machmir Mon May 16 2016 08:14:32 GMT+0300 (IDT) 
  Sof Zman Shma      Mon May 16 2016 11:56:00 GMT+0300 (IDT) 
  Sof Zman Tfilla    Mon May 16 2016 12:56:36 GMT+0300 (IDT) 
  Mincha Gedola      Mon May 16 2016 15:28:04 GMT+0300 (IDT) 
  Mincha Ketana      Mon May 16 2016 18:29:50 GMT+0300 (IDT) 
  Plag Hamincha      Mon May 16 2016 19:45:34 GMT+0300 (IDT) 
  Tzeit              Mon May 16 2016 21:33:47 GMT+0300 (IDT) 
  Neitz Hachama      Mon May 16 2016 08:54:14 GMT+0300 (IDT) 
  Shkiah             Mon May 16 2016 21:01:18 GMT+0300 (IDT)
node.js:758
        throw new TypeError('invalid pid');
        ^

TypeError: invalid pid
    at process.kill (node.js:758:15)
    at Object.<anonymous> (/Users/asher/.npm-packages/lib/node_modules/hebcal/bin/hebcal.js:218:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

It happens when you call process.kill(); at line 218 of hebcal.js

I hope there is a fix
Thanks
Asher

**Comment by Scimonster** [comment]
This is what happens when code isn't tested properly...
process.kill() tries to kill a specified process, not the current one.
There's a different function for that.

On Tuesday, May 17, 2016, Asher Szmulewicz <notifications@github.com> wrote:

> Hi,
> I just installed hebcal thru npm global on a mac and I always get the
> following error after the hebcaljs command e.g.
> $ hebcaljs -T
> 9 Iyyar 5776
>
> Times:
> Chatzot Mon May 16 2016 14:57:46 GMT+0300 (IDT)
> Chatzot Night Mon May 16 2016 02:57:45 GMT+0300 (IDT)
> Alot Hashachar Mon May 16 2016 07:49:28 GMT+0300 (IDT)
> Misheyakir Mon May 16 2016 08:09:01 GMT+0300 (IDT)
> Misheyakir Machmir Mon May 16 2016 08:14:32 GMT+0300 (IDT)
> Sof Zman Shma Mon May 16 2016 11:56:00 GMT+0300 (IDT)
> Sof Zman Tfilla Mon May 16 2016 12:56:36 GMT+0300 (IDT)
> Mincha Gedola Mon May 16 2016 15:28:04 GMT+0300 (IDT)
> Mincha Ketana Mon May 16 2016 18:29:50 GMT+0300 (IDT)
> Plag Hamincha Mon May 16 2016 19:45:34 GMT+0300 (IDT)
> Tzeit Mon May 16 2016 21:33:47 GMT+0300 (IDT)
> Neitz Hachama Mon May 16 2016 08:54:14 GMT+0300 (IDT)
> Shkiah Mon May 16 2016 21:01:18 GMT+0300 (IDT)
> node.js:758
> throw new TypeError('invalid pid');
> ^
>
> TypeError: invalid pid
> at process.kill (node.js:758:15)
> at Object.
> (/Users/asher/.npm-packages/lib/node_modules/hebcal/bin/hebcal.js:218:9)
> at Module._compile (module.js:435:26)
> at Object.Module._extensions..js (module.js:442:10)
> at Module.load (module.js:356:32)
> at Function.Module._load (module.js:311:12)
> at Function.Module.runMain (module.js:467:10)
> at startup (node.js:136:18)
> at node.js:963:3
>
> It happens when you call process.kill(); at line 218 of hebcal.js
>
> I hope there is a fix
> Thanks
> Asher
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hebcal/hebcal-js/issues/27>
>


-- 
Sent from Gmail Mobile

**Comment by ashersz** [comment]
Thanks
I changed the code to process.exit() and it works like a charm
Asher

**Comment by Scimonster** [comment]
Will you please create a pull request with this change? Don't forget to
bump the patch number in the version.

On Tuesday, May 17, 2016, Asher Szmulewicz <notifications@github.com> wrote:

> Thanks
> I changed the code to process.exit() and it works like a charm
> Asher
>
> On Tue, May 17, 2016 at 9:32 AM, Scimonster <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > This is what happens when code isn't tested properly...
> > process.kill() tries to kill a specified process, not the current one.
> > There's a different function for that.
> >
> > On Tuesday, May 17, 2016, Asher Szmulewicz <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Hi,
> > > I just installed hebcal thru npm global on a mac and I always get the
> > > following error after the hebcaljs command e.g.
> > > $ hebcaljs -T
> > > 9 Iyyar 5776
> > >
> > > Times:
> > > Chatzot Mon May 16 2016 14:57:46 GMT+0300 (IDT)
> > > Chatzot Night Mon May 16 2016 02:57:45 GMT+0300 (IDT)
> > > Alot Hashachar Mon May 16 2016 07:49:28 GMT+0300 (IDT)
> > > Misheyakir Mon May 16 2016 08:09:01 GMT+0300 (IDT)
> > > Misheyakir Machmir Mon May 16 2016 08:14:32 GMT+0300 (IDT)
> > > Sof Zman Shma Mon May 16 2016 11:56:00 GMT+0300 (IDT)
> > > Sof Zman Tfilla Mon May 16 2016 12:56:36 GMT+0300 (IDT)
> > > Mincha Gedola Mon May 16 2016 15:28:04 GMT+0300 (IDT)
> > > Mincha Ketana Mon May 16 2016 18:29:50 GMT+0300 (IDT)
> > > Plag Hamincha Mon May 16 2016 19:45:34 GMT+0300 (IDT)
> > > Tzeit Mon May 16 2016 21:33:47 GMT+0300 (IDT)
> > > Neitz Hachama Mon May 16 2016 08:54:14 GMT+0300 (IDT)
> > > Shkiah Mon May 16 2016 21:01:18 GMT+0300 (IDT)
> > > node.js:758
> > > throw new TypeError('invalid pid');
> > > ^
> > >
> > > TypeError: invalid pid
> > > at process.kill (node.js:758:15)
> > > at Object.
> > >
> (/Users/asher/.npm-packages/lib/node_modules/hebcal/bin/hebcal.js:218:9)
> > > at Module._compile (module.js:435:26)
> > > at Object.Module._extensions..js (module.js:442:10)
> > > at Module.load (module.js:356:32)
> > > at Function.Module._load (module.js:311:12)
> > > at Function.Module.runMain (module.js:467:10)
> > > at startup (node.js:136:18)
> > > at node.js:963:3
> > >
> > > It happens when you call process.kill(); at line 218 of hebcal.js
> > >
> > > I hope there is a fix
> > > Thanks
> > > Asher
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/hebcal/hebcal-js/issues/27>
> > >
> >
> >
> > --
> > Sent from Gmail Mobile
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/hebcal/hebcal-js/issues/27#issuecomment-219631083>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/hebcal/hebcal-js/issues/27#issuecomment-219631762>
>


-- 
Sent from Gmail Mobile

**Comment by ashersz** [comment]
OK
Asher

**Comment by Scimonster** [comment]
Has been fixed
