### ISSUE TITLE
Havdalah returns correct havdalah time but for Friday instead of Saturday

### ISSUE THREAD

**Issue by dannycohn** [hebcal/hebcal-js#30]
`
var today = hebcal.find('today')[0];
var havdalah = today.havdalah();
`

Run this on a Saturday (or set the computer's clock to Saturday). The time components in havdalah will be correct, but the date will be for Friday.

**Comment by Scimonster** [comment]
Or you know, just ask it for a Saturday date. ;)

I am able to reproduce this bug, but i am quite confused as to what is going on here. My own code has outsmarted me here. I think it has something to do with the location being set, or not.

**Comment by Scimonster** [comment]
Seems related to #9.

**Comment by Scimonster** [comment]
Has been fixed in the latest version.
