### ISSUE TITLE
Display proper Hebrew year without ה

### ISSUE THREAD

**Issue by 20Fourteen** [hebcal/hebcal-js#32]
Hi,
the following basic script will load the current date but with diacritics

`<script type="text/javascript" charset="utf-8" src="http://hebcal.com/etc/hdate-he.js">var hebdate Hebcal.HDate();  console.log(hebdate);</script>`

This displays: י״ב בְּתַמּוּז תשע״ו

Is there a way it can be called and displayed without the diacritics?

Thanks

**Comment by efroim102** [comment]
@20Fourteen Are you seriously using new as a variable name? isn't it a reserved keyword?

**Comment by 20Fourteen** [comment]
Not in production, this is an alpha of a dev test

**Comment by 20Fourteen** [comment]
Okay, I got it.

I was using the wrong library.

It works now

`<script type="text/javascript" charset="utf-8" src="https://rawgit.com/hebcal/hebcal-js/master/client/hebcal.min.js"></script>
<script>
	var day = new Hebcal.HDate().toString('h');
	document.write(day);
</script>`

Any way to remove the **ה** from the תשע"ו ?

**Comment by 20Fourteen** [comment]
Anyone?

Is this project abandoned?

**Comment by Scimonster** [comment]
You seem to have solved your issue, right?

**Comment by 20Fourteen** [comment]
No,

I was using the wrong library, but once sorted I'm facing this:

<script type="text/javascript" charset="utf-8" src="https://rawgit.com/hebcal/hebcal-js/master/client/hebcal.min.js"></script> <script> var day = new Hebcal.HDate().toString('h'); document.write(day); </script>

Result is: י"ג תמוז התשע"ו

Any way to remove the ה from the תשע"ו ?
Which argument 

Okay, I got it.

I was using the wrong library.

It works now

<script type="text/javascript" charset="utf-8" src="https://rawgit.com/hebcal/hebcal-js/master/client/hebcal.min.js"></script> <script> var day = new Hebcal.HDate().toString('h'); document.write(day); </script>

Result is: י"ג תמוז התשע"ו

Any way to remove the ה from the תשע"ו ?

**Comment by 20Fourteen** [comment]
How is this achieved here?
https://gist.github.com/mjradwin/08bcc39a1d2b3de7491f#file-hebdate-he-html

By the way there is a problem with the HTTPS on this page
https://www.hebcal.com/home/40/displaying-todays-hebrew-date-on-your-website

**Comment by Scimonster** [comment]
I'm not in charge of the website. It's possible those JS files are actually generated by server-side code using C.

As of right now there's no simple way to get the date without the ה. You could use a regex to remove it:

`var day = new Hebcal.HDate().toString('h'); document.write(day.replace(' ה',' '))`

This should be safe as no month name starts with ה.

**Comment by 20Fourteen** [comment]
I know about a regex, I wanted to do it cleanly and hoped there's an argument for it.

Perhaps getting the Gregorian date and converting day, month and year separately will yield the desired result, I wish the code would have something like `HDateFull` for ה'תשעו and `HDate `for תשעו

Thanks

**Comment by 20Fourteen** [comment]
For anyone seeking the same:, here is the code:
`var day = new Hebcal.HDate().toString('h').replace('\u05D4','');`

**Comment by Scimonster** [comment]
That's a bit risky -- it'll mess up on the 5th or 25th of the month, and any year that ends in 5. You should use my regex which also includes a space before the letter.

**Comment by 20Fourteen** [comment]
Correct, I missed that, will edit (for the copy and paste people).

Fixed :+1:
