### ISSUE TITLE
Just wanna say thanks :)

### ISSUE THREAD

**Issue by shlomizadok** [hebcal/hebcal-js#41]
Hey -- I have started using hebcal-js with in a React project, and it works perfectly - so thanks a lot for that ❤️ 

 (it is still a secret project so I can't share yet - will share soom)

**Comment by Scimonster** [comment]
Glad to hear. :) Let me know when it's done, and don't forget hebcal is
released under the GPL.

**Comment by shlomizadok** [comment]
👍
