### ISSUE TITLE
Fetch next Torah Portion?

### ISSUE THREAD

**Issue by mcblum** [hebcal/hebcal-js#45]
Hi! Thanks for providing this API. We're wondering what the best way is to query the API and get the next Torah portion. We can query by month but if the next Shabbat is in the following month, then the response doesn't have what we need. Is there a param to pass to request only the next Torah portion? Here's the API call we're currently experimenting with:

`http://www.hebcal.com/hebcal/?v=1&year=now&s=on&month={month}&cfg=json&geo=zip&zip={zip}`

Thank you for any help with this!
Matt

**Comment by Scimonster** [comment]
Hi Matt, this repository is for the Hebcal JavaScript code. The API on hebcal.com is in a different repo: hebcal/hebcal. You may want to post your question there. Best of luck!
