### ISSUE TITLE
setCity() doesn't work

### ISSUE THREAD

**Issue by icarpis** [hebcal/hebcal-js#50]
I'm trying to get the Jerusalem candle lighting time for the coming Shabat by the following code snippet:
```
var hebDate = new Hebcal.HDate();
hebDate.setCity('Jerusalem');
var d = hebDate.after(5).candleLighting();
```

For some reason I'm getting the same time no matter if I call to setCity or not.

**Comment by mjradwin** [comment]
I don't think you can call setCity on an HDate object.

According to the README, you should do:

var year = new Hebcal();

year.setCity('Jerusalem');


--

**Comment by icarpis** [comment]
Thank you @mjradwin, but I still get unreasonable times.

**Comment by mjradwin** [comment]
@Scimonster can you take a look?

**Comment by Scimonster** [comment]
It seems that the call to `after()` made it lose the location data. Fixed now.

(You can set the location directly on an HDate BTW.)
