### ISSUE TITLE
Sunrise and sunset are not exact

### ISSUE THREAD

**Issue by avrAhituv** [hebcal/hebcal-js#51]
Thank you very much, but i find a bug..

You use the [suncalc](https://github.com/mourner/suncalc) library to calculate sunrise and sunset times.
but times are not accurate, for example:
today, 30-08-2018 the sunrise is: 06:13 in jerusalem as can be seen on the site [yeshiva.org.il](https://www.yeshiva.org.il/calendar/timestable/).
![sunris-yeshiva-site](https://user-images.githubusercontent.com/15003252/44852888-15165d00-ac6d-11e8-9b9b-1a93c9ac0b8e.png)
but the library tells me that time is 06:25..
![sunrisejson](https://user-images.githubusercontent.com/15003252/44852898-1cd60180-ac6d-11e8-9cac-8f1c5a76b793.png)

i see the suncalc calculate the sunrise like this:
`var times = SunCalc.times = [
    [-0.833, 'sunrise',       'sunset'      ],
    [  -0.3, 'sunriseEnd',    'sunsetStart' ],
    [    -6, 'dawn',          'dusk'        ],
    [   -12, 'nauticalDawn',  'nauticalDusk'],
    [   -18, 'nightEnd',      'night'       ],
    [     6, 'goldenHourEnd', 'goldenHour'  ]
];
`
and in order for me to get the right times, I have to run over the sunrise to -2.4
the same is true of sunset..

Who can help me??
Thanks!

**Comment by Scimonster** [comment]
I think there are differing opinions as to when sunrise/sunset get counted. You can try to add your time to suncalc's list, and then overwrite HDate.prototype.sunrise and sunset, so that Hebcal will calculate zmanim according to your adjustment.

**Comment by Scimonster** [comment]
On second thought, this is likely connected to #48, where latitude and longitude had gotten reversed and as such it was calculating for the wrong place.

**Comment by Scimonster** [comment]
Yep, seems to have been #48. Should be fixed now.

**Comment by avrAhituv** [comment]
I checked now, and it works fine!
Thanks!!!
