### ISSUE TITLE
Wrong gregorian date prior to greg. year 1

### ISSUE THREAD

**Issue by JerryBels** [hebcal/hebcal-js#55]
Hello,

    var hdate = new Hebcal.HDate(18, 10, 3761);
    hdate.greg() => Mon Jan 01 0001 00:00:00 GMT+0220

And whenever we go under that, it's completely broken. The day before :

    var hdate = new Hebcal.HDate(17, 10, 3761);
    hdate.greg() => Thu Dec 31 -504 00:00:00 GMT+0220

500 years before : 

    var hdate = new Hebcal.HDate(17, 10, 3261);
    Tue Jan 03 -1003 00:00:00 GMT+0220

And one more day before : 

    var hdate = new Hebcal.HDate(16, 10, 3261);
    hdate.greg() => Tue Jan 01 -899 00:00:00 GMT+0220

That's a very big issue for me !

**Comment by mjradwin** [comment]
Hebcal wasn't designed to handle anything before Gregorian year 1.

**Comment by JerryBels** [comment]
@mjradwin okay, that's very problematic for the app I'm doing... Have you a recommandation of some sort to achieve what I'm trying to ?

**Comment by Scimonster** [comment]
It's going to be inaccurate before ~350CE anyways because that's when the calendar was switched to calculated instead of based on observation.
