### ISSUE TITLE
Get next/previous month

### ISSUE THREAD

**Issue by tamarklg** [hebcal/hebcal-js#69]
I'm using your library and it's very helpful...

I came across a little bug:
When I try to add/subtract 1 month to/from a date that is the last day of full month (30 days),
the result is - the first day of next 2 months.
e.g.
ל סיון + חודש 1 = א אב

**Comment by Scimonster** [comment]
What is your expected behavior? It tries to add a month to be ל תמוז, which doesn't exist, so it rolls over to א אב.

**Comment by tamarklg** [comment]
I expect it to behave like moment.js.
When you try to add 1 month to: 31/10/2019, the result is: 30/11/2019.

**Comment by Scimonster** [comment]
So this behavior is by design in this library and changing it would be a
breaking change

**Comment by tamarklg** [comment]
Thanks
