### ISSUE TITLE
PR proposal: Add JSDoc types

### ISSUE THREAD

**Issue by barakplasma** [hebcal/hebcal-js#70]
Would you accept a PR which added JSDoc types?

For example:

```javascript
/**
 * @typedef {number | [number, number]} locationCoordinate
 */
/**
 * @param {locationCoordinate} lat
 * @param {locationCoordinate} lon
 */
HebcalProto.setLocation = function(lat, lon) {
	this.months.forEach(function(m){
		m.setLocation(lat, lon);
	});
	return this;
};
```

This could assist users of VS Code with Intellisense via JSDoc. Additionally, lets us run a bit of Typescript checking on the library. See also  https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc

**Comment by Scimonster** [comment]
That would be awesome!

**Comment by Arrow7000** [comment]
@barakplasma I'd be really grateful if you did this!
