### ISSUE TITLE
Release new version to NPM

### ISSUE THREAD

**Issue by gdoron** [hebcal/hebcal-js#73]
Hi,

I noticed a few bugs in the names of some of the events, I checked the source code, and it was correct there, after 15 minutes of puzzling around, I noticed it was just fixed on GitHub but not released on NPM.

Would it be possible to release a new version to NPM that includes #67 ?

Thanks a lot for your hard work!

**Comment by Scimonster** [comment]
Yes, of course. Pushed v2.3.2 now.
